### ISSUE TITLE
Changed commit history

### ISSUE THREAD

**Issue by pchaigno** [KatrinaHoffert/Sublime-Text-TXL-syntax#2]
GitHub.com uses this repository to highlight TXL files. Because of this, it is referenced in [the Linguist repository](https://github.comgithub/linguist). In particular, Linguist references commit c1c98dfa.

We have a build failure at github/linguist because commit c1c98dfa doesn't seem to exist in the commit history anymore. Did you recently forced push to your master branch?

Thank you for any information you might have.

**Comment by KatrinaHoffert** [comment]
Huh, wasn't aware of any third party dependencies on this repo. Sorry. Yeah, there's been a forced push recently to fix the associated account names, which would have recreated the branch IDs. What was previous c1c98df is now 614cf83.

**Comment by pchaigno** [comment]
Okay, no problem. I'll fix it on our side :-)
